[package]
name = "famiko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.16"
pixels = "0.9.0"
pretty-hex = "0.2.1"
winit = "0.26.1"
winit_input_helper = "0.11.1"
